version: "3.3"
services: 
  portfolio_ptichka:
    restart: always
    build: .
    container_name: portfolio_ptichka
    ports:
      - 8081:8081
    expose:
      - 8081
    environment:
      - VIRTUAL_HOST=elizabethispravnikova.ml,www.elizabethispravnikova.ml
      - LETSENCRYPT_HOST=elizabethispravnikova.ml,www.elizabethispravnikova.ml
      - VIRTUAL_PORT=8081
      - VIRTUAL_NETWORK=proxy-network
networks:
  default: 
    external: 
      name: proxy-network